services:
  sales:
    build:
      dockerfile: Dockerfile.sales
    ports:
    - "8080:80"
    links:
    - mysqlito
    - monguito
    volumes:
    - ./Sales:/var/www/html
  products:
    build:
      dockerfile: Dockerfile.products
    ports:
    - "8081:80"
    links:
    - mysqlito
    - monguito
    volumes:
    - ./Products:/var/www/html
  mysqlito:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=mai
    volumes:
    - mysql-data:/var/lib/mysql
  monguito:
    image: mongo
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mai
    - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
    - mongo-data:/data/db
volumes:
  mysql-data:
  mongo-data:
